### ISSUE TITLE
Rename to "Padyakke One"

### ISSUE THREAD

**Issue by davelab6** [DunwichType/Padyakke_Libre#10]
Since this is a single style typeface, I would like to request renaming it to `Padyakke One` so that when i the future the family is fleshed out, the initial single style family can be de-listed and a new full-weighted family listed as `Padyakke` and `Padyakke Extended`

**Comment by davelab6** [comment]
https://github.com/erinmclaughlin/BhuTuka-One is set up like this

**Comment by DunwichType** [comment]
How about “Wide Padyakke” or “Padyakke Wide”? Earlier versions had no indicator that this was a wide font and Indian testers all thought I had just completely botched the proportions of the writing system.

**Comment by davelab6** [comment]
One is still needed since the family can be expanded. I can see how specifying the width is needed :) 

So that would be "Padyakke Wide One" - but @aoifemooney is using "Family Extended" in https://github.com/aoifemooney/makingbiorhyme/tree/gh-pages/Releases/OTFS - and @erinmclaughlin has not included a width term in the family name at https://github.com/erinmclaughlin/BhuTuka-One

I think Wide is less wide than Extended, and since this is very wide, Extended would be better.

So `Padyakke Extended One` and `BhuTuka Extended One` would be best, I think.

**Comment by davelab6** [comment]
@erinmclaughin and @aoifemooney what do you think?

**Comment by erinmclaughlin** [comment]
Yeah, I think that's a very good idea to include the width... but would calling it Expanded Thin be more descriptive? Or do you want to keep the Expanded One thing, as it keeps it in line with all of the other "one"s ?On March 15, 2016 at 12:23 PM Dave Crossland notifications@github.com wrote:@erinmclaughin and @aoifemooney what do you think?—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by davelab6** [comment]
I don't want to name the weight in the family name because the weight is specified in the API - but width is not

**Comment by aoifemooney** [comment]
I think this makes sense, 'Extended One', that is...

**Comment by erinmclaughlin** [comment]
Cool, I'll change mine! :)On March 15, 2016 at 12:52 PM aoifemooney notifications@github.com wrote:I think this makes sense, 'Extended One', that is...—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by erinmclaughlin** [comment]
Ergh, Ok one more question... If that's the family name, what's the style name?On March 15, 2016 at 12:52 PM aoifemooney notifications@github.com wrote:I think this makes sense, 'Extended One', that is...—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by davelab6** [comment]
Single style families must always have a Weight Class of 400 and a
subfamily (style) name of Regular

**Comment by erinmclaughlin** [comment]
Great! Ok phew :) ThanksOn March 15, 2016 at 9:55 PM Dave Crossland notifications@github.com wrote:Single style families must always have a Weight Class of 400 and a subfamily (style) name of Regular—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by DunwichType** [comment]
Renamed to “Padyakke Extended One”
